## grid search CV

A tecnique used to find the best parameter for your model .It create the grid of parameter for you model .

In [26]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import sklearn 
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR

In [27]:
dataset=pd.read_csv('C:\\Users\\muham\\Downloads\\placement.csv')
dataset

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[200 rows x 2 columns]

In [28]:
x=dataset.iloc[:,:-1]
x

     cgpa
0    6.89
1    5.12
2    7.82
3    7.42
4    6.94
..    ...
195  6.93
196  5.89
197  7.21
198  7.63
199  6.22

[200 rows x 1 columns]

In [29]:
y=dataset.iloc[:,-1:]
y

     package
0       3.26
1       1.98
2       3.25
3       3.67
4       3.57
..       ...
195     2.46
196     2.57
197     3.24
198     3.96
199     2.33

[200 rows x 1 columns]

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [32]:

from sklearn.model_selection import GridSearchCV

model = SVR(kernel='linear')

param_grid = {
    'C': [0.1, 1, 10, 100]
}

grid = GridSearchCV(model, param_grid, cv=5)
grid.fit(x_train, y_train.squeeze())
print(grid.best_params_)

{'C': 10}