In [19]:
import numpy as np 
import pandas as pd 
import sklearn 
from sklearn.preprocessing import OneHotEncoder,LabelEncoder,OrdinalEncoder,StandardScaler
from sklearn.impute import SimpleImputer

In [20]:
dataset=pd.read_csv("C:\\Users\\muham\\OneDrive\\Documents\\New folder\\employee_dataset.csv")

In [21]:
dataset

,Age,Salary,Experience,Gender,Department,Education,City,Purchased
0,25.0,50000.0,2.0,Male,IT,Bachelor,Lahore,Yes
1,30.0,65000.0,5.0,Female,HR,Master,Karachi,No
2,NaN,72000.0,7.0,Male,Finance,Bachelor,Islamabad,Yes
3,28.0,NaN,4.0,Female,IT,Master,Peshawar,No
4,35.0,85000.0,10.0,Male,Finance,PhD,Lahore,Yes
5,40.0,90000.0,12.0,Female,HR,Master,Karachi,Yes
6,27.0,58000.0,NaN,Male,IT,Bachelor,Quetta,No
7,NaN,61000.0,3.0,Female,Marketing,Bachelor,Lahore,No
8,32.0,75000.0,8.0,Male,Finance,Master,Islamabad,Yes
9,29.0,67000.0,5.0,Female,IT,Bachelor,Karachi,No
10,45.0,110000.0,20.0,Male,Management,PhD,Lahore,Yes
11,38.0,95000.0,15.0,Female,HR,Master,NaN,Yes
12,26.0,54000.0,2.0,Male,Marketing,Bachelor,Peshawar,No
13,31.0,73000.0,6.0,Female,Finance,Master,Quetta,Yes
14,34.0,82000.0,9.0,NaN,IT,Bachelor,Islamabad,Yes

### To check the missing  value

In [22]:
dataset.isnull().sum()

Age           2
Salary        1
Experience    1
Gender        1
Department    0
Education     0
City          1
Purchased     0
dtype: int64

In [ ]:
imputer=SimpleImputer(strategy='mean')
dataset[['Age','Salary','Experience']]=imputer.fit_transform(dataset[['Age','Salary','Experience']])

In [ ]:
dataset
## we can only achive this in pandas like
num_col=['Age','Salary','Experience']
for col in num_col:
    dataset[col]=dataset[col].fillna(dataset[col].mean())
dataset
for col in num_col:
    dataset[col]=dataset[col].fillna(dataset[col].mean())
dataset

    Age  Salary  Experience  Gender  Department Education       City Purchased
0    25   50000           2    Male          IT  Bachelor     Lahore       Yes
1    30   65000           5  Female          HR    Master    Karachi        No
2    32   72000           7    Male     Finance  Bachelor  Islamabad       Yes
3    28   74071           4  Female          IT    Master   Peshawar        No
4    35   85000          10    Male     Finance       PhD     Lahore       Yes
5    40   90000          12  Female          HR    Master    Karachi       Yes
6    27   58000           7    Male          IT  Bachelor     Quetta        No
7    32   61000           3  Female   Marketing  Bachelor     Lahore        No
8    32   75000           8    Male     Finance    Master  Islamabad       Yes
9    29   67000           5  Female          IT  Bachelor    Karachi        No
10   45  110000          20    Male  Management       PhD     Lahore       Yes
11   38   95000          15  Female          HR    Master     Lahore       Yes
12   26   54000           2    Male   Marketing  Bachelor   Peshawar        No
13   31   73000           6  Female     Finance    Master     Quetta       Yes
14   34   82000           9  Female          IT  Bachelor  Islamabad       Yes

### now we want to fill the catagorical values

In [ ]:

imputer=SimpleImputer(strategy='most_frequent')
dataset[['Gender','City']]=imputer.fit_transform(dataset[['Gender','City']])
# we can achive this in pandas 
num_col=['City','Gender']
for col in num_col:
    dataset[col]=dataset[col].fillna(dataset[col].mode())
dataset

    Age  Salary  Experience  Gender  Department Education       City Purchased
0    25   50000           2    Male          IT  Bachelor     Lahore       Yes
1    30   65000           5  Female          HR    Master    Karachi        No
2    32   72000           7    Male     Finance  Bachelor  Islamabad       Yes
3    28   74071           4  Female          IT    Master   Peshawar        No
4    35   85000          10    Male     Finance       PhD     Lahore       Yes
5    40   90000          12  Female          HR    Master    Karachi       Yes
6    27   58000           7    Male          IT  Bachelor     Quetta        No
7    32   61000           3  Female   Marketing  Bachelor     Lahore        No
8    32   75000           8    Male     Finance    Master  Islamabad       Yes
9    29   67000           5  Female          IT  Bachelor    Karachi        No
10   45  110000          20    Male  Management       PhD     Lahore       Yes
11   38   95000          15  Female          HR    Master     Lahore       Yes
12   26   54000           2    Male   Marketing  Bachelor   Peshawar        No
13   31   73000           6  Female     Finance    Master     Quetta       Yes
14   34   82000           9  Female          IT  Bachelor  Islamabad       Yes

In [32]:
dataset

,Age,Salary,Experience,Gender,Department,Education,City,Purchased
0,25.000000,50000.000000,2.000000,Male,IT,Bachelor,Lahore,Yes
1,30.000000,65000.000000,5.000000,Female,HR,Master,Karachi,No
2,32.307692,72000.000000,7.000000,Male,Finance,Bachelor,Islamabad,Yes
3,28.000000,74071.428571,4.000000,Female,IT,Master,Peshawar,No
4,35.000000,85000.000000,10.000000,Male,Finance,PhD,Lahore,Yes
5,40.000000,90000.000000,12.000000,Female,HR,Master,Karachi,Yes
6,27.000000,58000.000000,7.714286,Male,IT,Bachelor,Quetta,No
7,32.307692,61000.000000,3.000000,Female,Marketing,Bachelor,Lahore,No
8,32.000000,75000.000000,8.000000,Male,Finance,Master,Islamabad,Yes
9,29.000000,67000.000000,5.000000,Female,IT,Bachelor,Karachi,No
10,45.000000,110000.000000,20.000000,Male,Management,PhD,Lahore,Yes
11,38.000000,95000.000000,15.000000,Female,HR,Master,Lahore,Yes
12,26.000000,54000.000000,2.000000,Male,Marketing,Bachelor,Peshawar,No
13,31.000000,73000.000000,6.000000,Female,Finance,Master,Quetta,Yes
14,34.000000,82000.000000,9.000000,Female,IT,Bachelor,Islamabad,Yes

## now we want to encode the catagorical values

# oneHot encodig

In [52]:
catgoric_column=['Gender','Department','Education','City']
oHE=OneHotEncoder()
encode=oHE.fit_transform(dataset[catgoric_column]).toarray()
encoded_dataset=pd.DataFrame(encode,
                            columns=oHE.get_feature_names_out(catgoric_column))
encoded_dataset

,Gender_Female,Gender_Male,Department_Finance,Department_HR,Department_IT,Department_Management,Department_Marketing,Education_Bachelor,Education_Master,Education_PhD,City_Islamabad,City_Karachi,City_Lahore,City_Peshawar,City_Quetta
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
5,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
6,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
7,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
9,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
10,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
11,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
12,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
13,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
14,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0