## handling the catagorical value

In [60]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [61]:
import sklearn 
df=pd.read_csv("C:\\Users\\muham\\Downloads\\customer.csv")
df

    age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [62]:
# the column reviwe and aducation are the ordinal catagorical value
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split
X=df.iloc[:,:-1]
X

    age  gender   review education
0    30  Female  Average    School
1    68  Female     Poor        UG
2    70  Female     Good        PG
3    72  Female     Good        PG
4    16  Female  Average        UG
5    31  Female  Average    School
6    18    Male     Good    School
7    60  Female     Poor    School
8    65  Female  Average        UG
9    74    Male     Good        UG
10   98  Female     Good        UG
11   74    Male     Good        UG
12   51    Male     Poor    School
13   57  Female  Average    School
14   15    Male     Poor        PG
15   75    Male     Poor        UG
16   59    Male     Poor        UG
17   22  Female     Poor        UG
18   19    Male     Good    School
19   97    Male     Poor        PG
20   57  Female  Average    School
21   32    Male  Average        PG
22   18  Female     Poor        PG
23   96  Female     Good    School
24   16  Female  Average        PG
25   57  Female     Good    School
26   53  Female     Poor        PG
27   69  Female     Poor        PG
28   48    Male     Poor    School
29   83  Female  Average        UG
30   73    Male  Average        UG
31   22  Female     Poor    School
32   92    Male  Average        UG
33   89  Female     Good        PG
34   86    Male  Average    School
35   74    Male     Poor    School
36   34  Female     Good        UG
37   94    Male  Average        PG
38   45  Female     Good    School
39   76    Male     Poor        PG
40   39    Male     Good    School
41   23    Male     Good        PG
42   30  Female     Good        PG
43   27    Male     Poor        PG
44   77  Female  Average        UG
45   61    Male     Poor        PG
46   64  Female     Poor        PG
47   38  Female     Good        PG
48   39  Female     Good        UG
49   25  Female     Good        UG

In [63]:
Y=df.iloc[:,-1].to_frame()
Y

   purchased
0         No
1         No
2         No
3         No
4         No
5        Yes
6         No
7        Yes
8         No
9        Yes
10       Yes
11       Yes
12        No
13        No
14       Yes
15        No
16       Yes
17       Yes
18        No
19       Yes
20       Yes
21        No
22       Yes
23        No
24       Yes
25        No
26        No
27        No
28        No
29       Yes
30        No
31       Yes
32       Yes
33       Yes
34        No
35       Yes
36       Yes
37       Yes
38        No
39        No
40        No
41       Yes
42       Yes
43        No
44        No
45       Yes
46        No
47       Yes
48       Yes
49        No

## Ordinal Encoder 
### it is used when we want to presreve the order of our data like pooor,good ,and avarge it can oporate the input varible likw (X)

In [ ]:
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)
Ordinal=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])p

In [65]:
Ordinal
X_train=df[['review','education']]
X_test=df[['review','education']]

In [66]:
X_train_numerical=Ordinal.fit_transform(X_train)
X_test_numerical=Ordinal.fit_transform(X_test)
X_test_numerical

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

In [67]:
X_train_numerical

array([[1., 0.],
       [0., 1.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [2., 1.],
       [2., 1.],
       [2., 1.],
       [0., 0.],
       [1., 0.],
       [0., 2.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [2., 0.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [0., 2.],
       [2., 0.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [1., 0.],
       [0., 0.],
       [2., 1.],
       [1., 2.],
       [2., 0.],
       [0., 2.],
       [2., 0.],
       [2., 2.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [2., 1.],
       [2., 1.]])

## Lable encoder 
### this encoder are used when we want to give the label to uor data like yes/no.it only operate in one column at time so thats why we can use it in only target column

In [68]:
from sklearn.preprocessing import LabelEncoder
encoder=LabelEncoder()
encoder.fit_transform(df['purchased'])

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0])

## one hot enocder 
### The encoder are used in X input varible of the  dataset.it make the catogories of the data like if we have the three color like blue ,green and  red,
#### if we want to encode the the blue the array like this [1,0,0]
#### Green[0,1,0],red[0,0,1]
### means that it will make the three columnum for every feature

In [69]:
dataset=pd.read_csv('C:\\Users\\muham\\Downloads\\cars.csv')

In [70]:
dataset

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

## To Encode the nominal varible into one hot encoding

In [71]:
from sklearn.preprocessing import OneHotEncoder
x=dataset.iloc[:,:-1]
x

        brand  km_driven    fuel                 owner
0      Maruti     145500  Diesel           First Owner
1       Skoda     120000  Diesel          Second Owner
2       Honda     140000  Petrol           Third Owner
3     Hyundai     127000  Diesel           First Owner
4      Maruti     120000  Petrol           First Owner
...       ...        ...     ...                   ...
8123  Hyundai     110000  Petrol           First Owner
8124  Hyundai     119000  Diesel  Fourth & Above Owner
8125   Maruti     120000  Diesel           First Owner
8126     Tata      25000  Diesel           First Owner
8127     Tata      25000  Diesel           First Owner

[8128 rows x 4 columns]

In [72]:
y=dataset.iloc[:,-1].to_frame()
y

      selling_price
0            450000
1            370000
2            158000
3            225000
4            130000
...             ...
8123         320000
8124         135000
8125         382000
8126         290000
8127         290000

[8128 rows x 1 columns]

In [73]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [74]:
# ohe=OneHotEncoder(sparse_output=False)

# numerical=ohe.fit_transform([['fuel'	,'owner','brand']])
# print(numerical)
# encoded_df = pd.DataFrame(
#     numerical,
#     columns=ohe.get_feature_names_out(['fuel', 'owner', 'brand'],
#                                       index=dataset.index,
# ))

# print(encoded_df)

In [75]:
# print(ohe.get_feature_names_out(['fuel', 'owner', 'brand']))
# dataset1=dataset.drop(columns=['fuel'	,'owner','brand'])
# dataset1

In [76]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

ohe = OneHotEncoder(sparse_output=False)

encoded = ohe.fit_transform(dataset[['fuel', 'owner', 'brand']])

encoded_df = pd.DataFrame(
    encoded,
    columns=ohe.get_feature_names_out(['fuel', 'owner', 'brand'])
    # index=dataset.index
)

dataset = dataset.drop(columns=['fuel', 'owner', 'brand'])

dataset = pd.concat([dataset, encoded_df], axis=1)

print(dataset.head())

   km_driven  selling_price  fuel_CNG  fuel_Diesel  fuel_LPG  fuel_Petrol  \
0     145500         450000       0.0          1.0       0.0          0.0
1     120000         370000       0.0          1.0       0.0          0.0
2     140000         158000       0.0          0.0       0.0          1.0
3     127000         225000       0.0          1.0       0.0          0.0
4     120000         130000       0.0          0.0       0.0          1.0

   owner_First Owner  owner_Fourth & Above Owner  owner_Second Owner  \
0                1.0                         0.0                 0.0
1                0.0                         0.0                 1.0
2                0.0                         0.0                 0.0
3                1.0                         0.0                 0.0
4                1.0                         0.0                 0.0

   owner_Test Drive Car  ...  brand_Mitsubishi  brand_Nissan  brand_Opel  \
0                   0.0  ...               0.0           0.0         0.0
1                   0.0  ...               0.0           0.0         0.0
2                   0.0  ...               0.0           0.0         0.0
3                   0.0  ...               0.0           0.0         0.0
4                   0.0  ...               0.0           0.0         0.0

   brand_Peugeot  brand_Renault  brand_Skoda  brand_Tata  brand_Toyota  \
0            0.0            0.0          0.0         0.0           0.0
1            0.0            0.0          1.0         0.0           0.0
2            0.0            0.0          0.0         0.0           0.0
3            0.0            0.0          0.0         0.0           0.0
4            0.0            0.0          0.0         0.0           0.0

   brand_Volkswagen  brand_Volvo
0               0.0          0.0
1               0.0          0.0
2               0.0          0.0
3               0.0          0.0
4               0.0          0.0

[5 rows x 43 columns]

In [77]:
dataset.columns

Index(['km_driven', 'selling_price', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol', 'owner_First Owner', 'owner_Fourth & Above Owner',
       'owner_Second Owner', 'owner_Test Drive Car', 'owner_Third Owner',
       'brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia', 'brand_Land',
       'brand_Lexus', 'brand_MG', 'brand_Mahindra', 'brand_Maruti',
       'brand_Mercedes-Benz', 'brand_Mitsubishi', 'brand_Nissan', 'brand_Opel',
       'brand_Peugeot', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_Volvo'],
      dtype='str')