In [79]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt 
import sklearn 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

In [80]:
DataSet=pd.read_csv("C:\\Users\\muham\\Downloads\\student_dataset_null_categorical.csv")
DataSet

          Name  Gender   Age      City  Marks Grade Passed
0    Student_0    Male  24.0    Mardan     99     A    Yes
1    Student_1  Female   NaN       NaN     98     D    Yes
2    Student_2    Male  21.0      Swat     45     A     No
3    Student_3    Male  21.0     Kohat     55     D    Yes
4    Student_4    Male  22.0      Swat     68     D    Yes
..         ...     ...   ...       ...    ...   ...    ...
95  Student_95  Female  23.0      Swat     59     B    Yes
96  Student_96     NaN  23.0      Swat     95     D    Yes
97  Student_97  Female   NaN       NaN     47     C     No
98  Student_98  Female  18.0  Peshawar     46     A     No
99  Student_99    Male  26.0       NaN     42     B     No

[100 rows x 7 columns]

In [81]:
X=DataSet.iloc[:,:-1]
X

          Name  Gender   Age      City  Marks Grade
0    Student_0    Male  24.0    Mardan     99     A
1    Student_1  Female   NaN       NaN     98     D
2    Student_2    Male  21.0      Swat     45     A
3    Student_3    Male  21.0     Kohat     55     D
4    Student_4    Male  22.0      Swat     68     D
..         ...     ...   ...       ...    ...   ...
95  Student_95  Female  23.0      Swat     59     B
96  Student_96     NaN  23.0      Swat     95     D
97  Student_97  Female   NaN       NaN     47     C
98  Student_98  Female  18.0  Peshawar     46     A
99  Student_99    Male  26.0       NaN     42     B

[100 rows x 6 columns]

In [82]:
Y=DataSet.iloc[:,-1:]
Y

   Passed
0     Yes
1     Yes
2      No
3     Yes
4     Yes
..    ...
95    Yes
96    Yes
97     No
98     No
99     No

[100 rows x 1 columns]

## pipline

In [83]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer

In [84]:
numericFeature=["Age",	"Marks"]
catgoricFeature=["Name","Gender	","City","Grade"]

In [85]:
numericTransform=  Pipeline(steps=[
    'imputer',SimpleImputer(strategy='mean')])

In [86]:
catagoricTransfrom=Pipeline(steps=[
    'imputer',SimpleImputer(strategy='mostFrequent'),
    'encoder',OneHotEncoder(handle_unknown='ignore')
])

In [87]:
from sklearn.compose import ColumnTransformer

In [88]:
colmumnTrasnform=ColumnTransformer(transformers=['num',numericFeature,numericTransform,
                                   'cat',catagoricTransfrom,catgoricFeature])

In [ ]:
pip=Pipeline([
    ('imputer',SimpleImputer(strategy='mostFrequent')),
    ('encoder',OneHotEncoder(handle_unknown='ignore')),
    

])