In [36]:
import numpy as np
import pandas as pd
import sklearn 
from sklearn.datasets import make_classification

In [37]:
X,Y=make_classification(n_features= 6,n_redundant=0,n_informative=6,n_clusters_per_class=1)

In [38]:
df=pd.DataFrame(X,columns=["A","B","C","D","E","F"])

In [39]:
df
df['target']=Y
df

           A         B         C         D         E         F  target
0  -0.010719 -0.548198 -1.357877 -2.346867 -1.002833 -1.658361       1
1  -2.685844 -0.296736  0.145154 -0.902812 -1.295413 -3.575582       1
2  -1.378384  0.488241  1.004003 -1.370481  1.270730  2.238023       0
3   0.129111  2.267388 -2.969471 -0.967897 -2.916081 -1.398516       1
4  -0.670145 -0.876129 -0.133139  0.293464  1.923137  1.587040       0
..       ...       ...       ...       ...       ...       ...     ...
95 -1.826494  0.307035 -0.150293 -2.364753 -0.263659 -3.125488       1
96 -0.297258  1.880952 -1.910002 -2.568527  0.442098  0.266121       0
97  0.826528  1.864758 -1.500189 -1.599908 -1.651224 -0.607486       1
98 -1.514909  1.544980 -2.684603 -0.632032  0.885041  0.650321       0
99 -2.118587  1.346106 -2.122214  1.102972 -0.427236 -2.283438       1

[100 rows x 7 columns]

In [40]:
df.head(4)

          A         B         C         D         E         F  target
0 -0.010719 -0.548198 -1.357877 -2.346867 -1.002833 -1.658361       1
1 -2.685844 -0.296736  0.145154 -0.902812 -1.295413 -3.575582       1
2 -1.378384  0.488241  1.004003 -1.370481  1.270730  2.238023       0
3  0.129111  2.267388 -2.969471 -0.967897 -2.916081 -1.398516       1

In [41]:
df.shape

(100, 7)

In [42]:
def Sample_row(df,percent):
    return df.sample(int(percent * df.shape[0]),replace= True)

In [43]:
import random

def sample_col(df, percent):
    feature_cols = df.columns.to_list()[:-1]
    col = random.sample(
        feature_cols,
        int(percent * len(feature_cols))
    )
    return df[col]

In [44]:
d1=Sample_row(df,0.1)
d2=Sample_row(df,0.8)
d3=Sample_row(df,0.7)

In [45]:
from sklearn.tree import DecisionTreeClassifier
c1=DecisionTreeClassifier()
c2=DecisionTreeClassifier()
c3=DecisionTreeClassifier()

In [46]:
c1.fit(d1.iloc[:,:-1],d1.iloc[:,:-1])
c2.fit(d2.iloc[:,:-1],d2.iloc[:,:-1])
c3.fit(d3.iloc[:,:-1],d3.iloc[:,:-1])

ValueError: Unknown label type: continuous-multioutput. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.

In [ ]:
print(d1.columns)

Index(['A', 'B', 'C', 'D', 'E', 'F', 'taget'], dtype='str')

In [ ]:
print(d1["taget"].unique())
print(d1["taget"].dtype)

[0 1]
int64